"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_service_1 = require("../services/auth.service");
const auth_controller_1 = require("../controllers/auth.controller");
const router = (0, express_1.Router)();
router.post('/register', auth_controller_1.registerUser);
router.post("/login", auth_controller_1.loginUser);
router.post('/logout', auth_service_1.logout);
exports.default = router;
